let tools=[],activeCategory="",query="";
const categoryFallback=["AI & Automation","Writing & Research","Search & Investigation","Design & Images","Video & Audio","Developer Tools","Data & Analytics","Education & Learning","Documents & PDF","Productivity","Business & Finance","Security & Privacy"];
const stop=new Set(["the","a","an","for","to","of","and","or","with","my","this","that","i","need","want","find","get","make","use","on","in","it","is","how","can","please","me","do"]);
const normalize=t=>({...t,categories:[...new Set(t.categories||["Other"])],capabilities:t.capabilities||[],inputs:t.inputs||[],outputs:t.outputs||[],tags:t.tags||[]});
const hay=t=>[t.name,t.description,...t.categories,...t.capabilities,...t.inputs,...t.outputs,...t.tags].join(" ").toLowerCase();
const terms=q=>q.toLowerCase().replace(/[^a-z0-9+#.-]+/g," ").split(/\s+/).filter(x=>x&&!stop.has(x));
function score(t,q){let s=0,n=t.name.toLowerCase(),h=hay(t),d=t.description.toLowerCase();for(const x of terms(q)){if(n.includes(x))s+=20;if(t.categories.some(v=>v.toLowerCase().includes(x)))s+=12;if(t.tags.some(v=>v.toLowerCase().includes(x)))s+=9;if(t.capabilities.some(v=>v.toLowerCase().includes(x)))s+=8;if(t.inputs.some(v=>v.toLowerCase().includes(x)))s+=6;if(t.outputs.some(v=>v.toLowerCase().includes(x)))s+=5;if(d.includes(x))s+=3}if(h.includes(q.toLowerCase()))s+=10;return s}
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",""":"&quot;","'":"&#39;"}[m]));
function categories(){let set=new Set(categoryFallback);tools.forEach(t=>t.categories.forEach(c=>set.add(c)));return [...set].filter(x=>x!=="Other")}
function counts(){const c={};tools.forEach(t=>t.categories.forEach(x=>c[x]=(c[x]||0)+1));return c}
function renderFilters(){const c=counts(),list=document.querySelector("#categoryList");list.innerHTML='<button class="cat-btn '+(!activeCategory?"active":"")+'" data-cat="">All tools <span>'+tools.length+'</span></button>'+categories().map(x=>'<button class="cat-btn '+(activeCategory===x?"active":"")+'" data-cat="'+esc(x)+'">'+esc(x)+' <span>'+(c[x]||0)+'</span></button>').join("");list.querySelectorAll(".cat-btn").forEach(b=>b.onclick=()=>{activeCategory=b.dataset.cat;renderFilters();render();if(innerWidth<=680)document.querySelector("#filters").classList.remove("open")})}
function renderCategoryCards(){const c=counts();document.querySelector("#categoryCards").innerHTML=categories().map(x=>'<button class="category-card" data-cat="'+esc(x)+'"><b>'+esc(x)+'</b><span>'+(c[x]||0)+' tools</span></button>').join("");document.querySelectorAll(".category-card").forEach(b=>b.onclick=()=>{activeCategory=b.dataset.cat;renderFilters();render();document.querySelector("#tools").scrollIntoView({behavior:"smooth"});})}
function render(){let arr=tools.filter(t=>!activeCategory||t.categories.includes(activeCategory));if(query)arr=arr.map(t=>({...t,_score:score(t,query)})).filter(t=>t._score>0);const sort=document.querySelector("#sort").value;if(sort==="name")arr.sort((a,b)=>a.name.localeCompare(b.name));else if(sort==="category")arr.sort((a,b)=>(a.categories[0]||"").localeCompare(b.categories[0]||""));else arr.sort((a,b)=>(b._score||0)-(a._score||0)||a.name.localeCompare(b.name));document.querySelector("#resultCount").textContent=arr.length+" tool"+(arr.length===1?"":"s");document.querySelector("#resultsTitle").textContent=query?"Search results":activeCategory||"All tools";document.querySelector("#activeFilters").innerHTML=(activeCategory?'<button id="removeCat">'+esc(activeCategory)+' ×</button>':"")+(query?'<button id="removeQuery">“'+esc(query)+'” ×</button>':"");document.querySelector("#removeCat")?.addEventListener("click",()=>{activeCategory="";renderFilters();render()});document.querySelector("#removeQuery")?.addEventListener("click",()=>{query="";document.querySelector("#search").value="";render()});const box=document.querySelector("#results");box.innerHTML=arr.slice(0,100).map(t=>'<article class="tool-card"><div class="tool-top"><a class="tool-name" href="'+esc(t.url)+'" target="_blank" rel="noopener noreferrer">'+esc(t.name)+'</a><a class="open" href="'+esc(t.url)+'" target="_blank" rel="noopener noreferrer">Open ↗</a></div><p>'+esc(t.description)+'</p><div class="tags">'+t.categories.slice(0,3).map(x=>'<span class="tag">'+esc(x)+'</span>').join("")+'</div></article>').join("");document.querySelector("#empty").hidden=arr.length!==0}
function setQuery(v){query=v.trim();render()}
document.querySelector("#search").addEventListener("input",e=>setQuery(e.target.value));
document.querySelector("#sort").addEventListener("change",render);
document.querySelector("#clear").onclick=()=>{document.querySelector("#search").value="";setQuery("")};
document.querySelector("#reset").onclick=()=>{activeCategory="";query="";document.querySelector("#search").value="";renderFilters();render()};
document.querySelector("#mobileFilter").onclick=()=>document.querySelector("#filters").classList.add("open");
document.querySelector("#closeFilter").onclick=()=>document.querySelector("#filters").classList.remove("open");
document.querySelectorAll(".quick-search button").forEach(b=>b.onclick=()=>{document.querySelector("#search").value=b.dataset.query;setQuery(b.dataset.query);document.querySelector("#tools").scrollIntoView({behavior:"smooth"})});
window.addEventListener("keydown",e=>{if(e.key==="/"&&document.activeElement.tagName!=="INPUT"){e.preventDefault();document.querySelector("#search").focus()}if(e.key==="Escape"){document.querySelector("#filters").classList.remove("open")}});
async function load(){try{const r=await fetch("tools.json?"+Date.now(),{cache:"no-store"});tools=(await r.json()).map(normalize)}catch(e){tools=[]}renderFilters();renderCategoryCards();render()}
load();